@baseUrl = http://localhost:3001
@todoId = 1

###
GET {{baseUrl}}/health

###
GET {{baseUrl}}/api/ping

###
GET {{baseUrl}}/todo

###
POST {{baseUrl}}/todo/create-todo
Content-Type: application/json

{
  "todo": "learn react",
  "user": "alkis"
}

###
GET {{baseUrl}}/todo/user-todos/alkis

###
GET {{baseUrl}}/todo/{{todoId}}

###
POST {{baseUrl}}/todo/update-todo/{{todoId}}
Content-Type: application/json

{
  "completed": true
}

###
POST {{baseUrl}}/todo/delete-todo/{{todoId}}

###
POST {{baseUrl}}/todo/delete-all-user-todos/alkis